version: '3.8'

services:
  # Nginx container
  nginx:
    # Official nginx image based on alpine
    image: nginx:alpine
    # Expose nginx on port 6666
    ports:
      - 6666:80
    volumes:
      # Add phpinfo site
      - ./src:/src
      # Add nginx configuration
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    # Connect to both networks
    networks:
      - backend
      - frontend

  # PHP contriner
  php:
    # Official PHP-FPM image based on alpine
    image: php:fpm-alpine
    volumes:
      # Add phpinfo site
      - ./src:/src
    networks:
      - backend

# Define networks
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
