version: '3.8'

services:
  # Nginx container
  nginx:
    # Official nginx image based on alpine
    image: nginx:alpine
    # Expose nginx on port 6666
    ports:
      - 6666:80
    volumes:
      # Add phpinfo site
      - ./src:/src
      # Add nginx configuration
      - ./config/site.conf:/etc/nginx/conf.d/default.conf
    # Connect to both networks
    networks:
      - backend
      - frontend

  # PHP contriner
  php:
    # Official PHP-FPM image based on alpine
    image: php:fpm-alpine
    volumes:
      # Add phpinfo site
      - ./src:/src
    # Connect to backend network
    networks:
      - backend
  
  # MySQL contriner
  db:
    # Official MySQL image
    image: mysql:latest
    # Persist db in volume
    volumes:
      - db:/var/lib/mysql
    # Set weak password for testing
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    # Connect to backend network
    networks:
      - backend
  
  # phpMyAdmin container
  phpmyadmin:
    # Official phpMyAdmin FPM image based on alpine
    image: phpmyadmin:latest
    # Expose on port 6001
    ports:
      - 6001:80
    restart: always
    # Connect to backend network
    networks:
      - backend


# Define networks
networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

# Define volume for MySQL
volumes:
  db: